config/routes.rb
Rails.application.routes.draw do
  get 'roles/nominate_admin'
  get 'roles/remove_admin'
  get 'logout/destroy'
  devise_for :users


  # delete 'users/:id', to: 'home#destroy', as: 'delete_user'
  delete 'users/:id', to: 'home#destroy', as: :delete_user

  put 'toggle_role_user/:id', to: 'home#toggle_role_user', as: 'toggle_role_user'
  # put 'show/:id', to: 'projects#show', as: 'show_role_user'

  # Route spécifique pour la suppression d'un projet
  get '/logout', to: 'logout#destroy', as: :logout

  root "home#index"
  resources :projects

  post 'projects/:id/add_user', to: 'projects#add_user', as: 'project_add_user'

  get 'view', to: 'home#view'
  get 'index', to: 'projects#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :authenticate_user!

    # validates :name, presence: true
    # validates :role, inclusion: { in: %w[user admin] }

    def index
      @users = User.all
    end

    def view
      @users = User.all
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to view_path, notice: 'User was successfully deleted.'
    end

    def toggle_role_user

      # ce code se repete dans projects controller
        @user = User.find(params[:id])

        if @user.role == 'user'
          @user.update(role: 'admin')
        else
          @user.update(role: 'user')
        end
        redirect_to view_path, notice: "Le rôle de l'utilisateur a été modifié avec succès."
    end
    
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1><% if user_signed_in?  %></h1>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h1 class="text-center">Welcome <%= current_user.first_name %></h1>

          <%# <p>Signed in as <h3></h3></p> %>
            <p class='text-center'>To manage users, please sign in as an administrator.</p>

            <div style='display:flex;'>
                <p class="text-center p-2 m-4 rounded-lg mb-0" style=" height : 40px; flex-grow: 1; background-color: rgba(0, 0, 255, 0.2); border-radius: 7px;  ">
                    <%= link_to "Manage users", view_path, class: "text-decoration-none text-primary" %>
                </p>

                <p class="text-center p-2 m-4 rounded-lg mb-0" style=" height : 40px; flex-grow: 1; background-color: rgba(0, 0, 255, 0.2); border-radius: 7px; ">
                    <%= link_to "Manage projects", index_path, class: "text-decoration-none text-primary" %>
                </p>

                <p class='btn btn-danger m-4' style="flex-grow: 1;">
                    <%= link_to "Logout", logout_path, method: :delete, class: "text-decoration-none text-light "  %>
                </p>
            </div>

          <% else %>
            <p>Please sign in to access your account.</p>
            <p><%= link_to "Sign in", new_user_session_path, class: "text-decoration-none text-light btn btn-primary" %></p>
          
        </div>
      </div>
    </div>
  </div>
</div>

<%end%>

app/views/home/view.html.erb
    <div style=" background-color: rgba(0, 0, 255, 0.3); height:47px;">
        <br>
        <h2 style="text-align:center; ">
          Signed in as <%= current_user.first_name %>
        </h2><br>
    </div>
       
      <%# nav pannel %>
    <div style="display:flex; justify-content:center; background-color: rgba(0, 0, 255, 0.2); " >
      <p class="text-decoration-none m-4 btn btn-secondary ">
        <%= link_to "Welcome page", root_path, class: "text-decoration-none  text-white" %>
      </p>

      <p class="text-decoration-none m-4 btn btn-secondary ">
        <%= link_to "manage projects", index_path,class: "text-decoration-none  text-white" %>
      </p>

      <p class="btn btn-danger m-4 ">
          <%= link_to "Log out", logout_path, method: :delete, class: "text-decoration-none text-white  " %>
      </p>

    </div>

    <div class="text-center ">
        <span class="fw-bold  text-link" style="color: rgba(0, 50, 255, 0.8);"  >USERS LIST</span><br>
    </div><br>

<h1><% if user_signed_in?  %></h1>

<div class="container" style='padding-top: 1%; padding-bottom: 1%;'>
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card " >
        <div class="card-body">
                <%# <%if current_user.role == 'admin'%> 
            
            <% @users.each do |user| %>
                <div class="text-center border-bottom border-primary">
                    <span>
                        Name:<%= user.first_name  %>
                    </span> <br> 
                    <span>
                        Email:<%= user.email %>
                    </span>                          
                    <%# code de suppression %>
                    <div style="display:flex; justify-content:center;">
                        <span style="padding-right:40px;"> 
                            <%= form_tag delete_user_path(user), method: :delete, data: { confirm: 'Êtes-vous sûr de vouloir supprimer cet utilisateur?' } do %>    
                                <%= submit_tag 'Delete' ,style:"height:38px;" ,class:"btn btn-danger"%>
                            <% end %>
                        </span>
                    <%# code de basculement %>
                        <span>
                            <%= form_tag toggle_role_user_path(user), method: :put do %>    
                            <% if user.role == 'user' %>
                                <%= submit_tag 'Pass as admin', class: 'btn btn-primary' %>
                            <% else %>
                                <%= submit_tag 'Pass as user', class: 'btn btn-secondary' %>
                            <% end %>
                            <% end %>
                        </span>
                    </div>
                </div><br>
            <% end %>
                    
                <%# <%end%>

    </div>
   </div>
  </div>
 </div>
</div>
<% end %>
<%= yield %>