config/routes.rb
Rails.application.routes.draw do
  get 'roles/nominate_admin'
  get 'roles/remove_admin'
  get 'logout/destroy'
  devise_for :users


  # delete 'users/:id', to: 'home#destroy', as: 'delete_user'
  delete 'users/:id', to: 'home#destroy', as: :delete_user

  put 'toggle_role_user/:id', to: 'home#toggle_role_user', as: 'toggle_role_user'
  # put 'show/:id', to: 'projects#show', as: 'show_role_user'

  # Route spécifique pour la suppression d'un projet
  get '/logout', to: 'logout#destroy', as: :logout

  root "home#index"
  resources :projects

  post 'projects/:id/add_user', to: 'projects#add_user', as: 'project_add_user'

  get 'view', to: 'home#view'
  get 'index', to: 'projects#index'

end

app/models/project.rb
class Project < ApplicationRecord
    has_many :user_projects
    has_many :users, through: :user_projects
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_project, only: [:edit, :update, :destroy, :show, :add_user]

    def index
        @projects = Project.all
    end

    def new
        @project = Project.new
    end

    def show
        @project = Project.find(params['id'])
        @user_project = UserProject.new # Créer une nouvelle instance de UserProject


    end

    def create
        @project = Project.new(permitted_params)
        if @project.save
            redirect_to project_path(@project)
        else
            render :new
        end
        
    end

    def edit
    end

    def update
        if @project.update(permitted_params)
            redirect_to project_path(@project)
        else
            render :edit
        end
    end 

    def destroy
        @project = Project.find(params[:id])

        # Récupérer les utilisateurs associés au projet
        @users = @project.users
    
        # Supprimer les utilisateurs associés
        @users.destroy_all if @users.any?
        # @project = Project.find(params[:id])
        @project.destroy
        
        redirect_to projects_path, notice: "Le projet a été supprimé avec succès."
    end


    def add_user
        if current_user.role == 'admin'
          user = User.find_by(email: params[:email])
          if user
            if @project.users.include?(user)
              flash[:alert] = "L'utilisateur est déjà affecté à ce projet."
            else
              @project.users << user
              flash[:notice] = "L'utilisateur a été ajouté au projet avec succès."
            end
          else
            flash[:alert] = "L'utilisateur avec l'adresse e-mail fournie n'existe pas."
          end
        else
          flash[:alert] = "Vous n'êtes pas autorisé à effectuer cette action."
        end
        redirect_to project_path(@project)
    end

    protected

    def permitted_params
        params.require(:project).permit(:name, :description)
    end

    def set_project
        @project = Project.find(params['id'])
    end


end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<%# <h1>Edit Project</h1> %>

    <div style=" background-color: rgba(0, 0, 255, 0.3); height:47px;">
        <br>
        <h2 style="text-align:center; ">
          Signed in as <%= current_user.first_name %>
        </h2><br>
    </div>
       
      <%# nav pannel %>
    <div style="display:flex; justify-content:center; background-color: rgba(0, 0, 255, 0.2); " >
      <p class="text-decoration-none m-4 btn btn-secondary ">
        <%= link_to "Welcome page", root_path, class: "text-decoration-none  text-white" %>
      </p>

      <p class="text-decoration-none m-4 btn btn-secondary ">
        <%= link_to "manage projects", index_path,class: "text-decoration-none  text-white" %>
      </p>

      <p class="m-4 btn btn-secondary " >
          <%= link_to "new project", new_project_path, class: "text-decoration-none text-white" %>
      </p>

      <p class="btn btn-danger m-4 ">
          <%= link_to "Log out", logout_path, method: :delete, class: "text-decoration-none text-white  " %>
      </p>

    </div>

    <div class="text-center ">
          <span class="fw-bold  text-link" style="color: rgba(0, 50, 255, 0.8);"  >EDIT PROJECT </span><br>
    </div><br>

<div class="container" style='padding-top: 2%; padding-bottom: 2%;'>
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card " >
        <div class="card-body">
          <%# <h2 class="card-title text-center">Log in</h2> %>
          <%= form_with(model: @project, url: project_path(@project), method: :patch) do |form| %>
            <% if @project.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

                <ul>
                  <% @project.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            
              <div class="form-group">
                <%= form.label :name %>
                <span>
                  <%= form.text_field :name, class: "form-control" %>
                </span>
              </div><br>

              <div class="form-group">
                <%= form.label :description  %>
                <%= form.text_area :description, class: "form-control"  %>
              </div><br>

              <div class="form-actions text-center ">
                <span><%= form.submit class: "btn btn-primary" %></span>
                <span><%= link_to 'Back', project_path(@project), class: "btn btn-light border border-primary" %></span>
              </div>
          

              <p>
                <%# <%= link_to 'Back', project_path(@project), class: "btn btn-light border border-primary" %> 
              </p>
          <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>      

app/views/projects/index.html.erb
<% if user_signed_in? %>
        
        <div style=" background-color: rgba(0, 0, 255, 0.3); height:47px;">
          <br>
          <h2 style="text-align:center; ">
            Signed in as <%= current_user.first_name %>
          </h2><br>
        </div>
         
        <div style="display:flex; justify-content:center; background-color: rgba(0, 0, 255, 0.2); " >

          <p  class="text-decoration-none m-4 btn btn-secondary "   >
              <%= link_to "Welcome page", root_path , class: "text-decoration-none text-white " %>
          </p>
          
          <p class="m-4 btn btn-secondary " >
              <%= link_to "new project", new_project_path, class: "text-decoration-none text-white" %>
          </p>

          <p class="btn btn-danger m-4 ">
              <%= link_to "Log out", logout_path, method: :delete, class: "text-decoration-none text-white  " %>
          </p>

        </div>

  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
          
          <div class="text-center ">
            <span class="fw-bold  text-link" style="color: rgba(0, 50, 255, 0.8);"  >PROJECTS LIST </span><br>
            <em class="text-secondary">click on project for more options<em>
          </div><br>

          <% @projects.each do |project| %>

            <div> 
              <p class="text-center border-bottom text-muted border-primary">
                 <span>
                    <%= link_to project.name, project_path(project), class: "text-decoration-none text-blue" %>
                 </span>  <br> 
                 <em style="opacity:0.7;">  
                    <%= link_to project.description, project_path(project), class: "text-decoration-none text-dark text-secondary" %>
                 </em>
              </p>
               
            </div>

          <% end %>

      </div>
    </div>
  </div>  



<% end %>
<%= yield %>
   

app/views/projects/new.html.erb
    <div style=" background-color: rgba(0, 0, 255, 0.3); height:47px;">
        <br>
        <h2 style="text-align:center; ">
          Signed in as <%= current_user.first_name %>
        </h2><br>
    </div>
       
      <%# nav pannel %>
    <div style="display:flex; justify-content:center; background-color: rgba(0, 0, 255, 0.2); " >
      <p class="text-decoration-none m-4 btn btn-secondary ">
        <%= link_to "Welcome page", root_path, class: "text-decoration-none  text-white" %>
      </p>

      <p class="text-decoration-none m-4 btn btn-secondary ">
        <%= link_to "manage projects", index_path,class: "text-decoration-none  text-white" %>
      </p>

      <p class="btn btn-danger m-4 ">
          <%= link_to "Log out", logout_path, method: :delete, class: "text-decoration-none text-white  " %>
      </p>

    </div>

    <div class="text-center ">
          <span class="fw-bold  text-link" style="color: rgba(0, 50, 255, 0.8);"  >NEW PROJECT </span><br>
    </div><br>

<div class="container" style='padding-top: 2%; padding-bottom: 2%;'>
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card " >
        <div class="card-body">
            <%= simple_form_for @project do |f| %>
            <div>
              
                  <p class="form-group">
                    <label for="name">Name</label>
                    <input type="text" id="name" name="project[name]" class="form-control">
                  </p>

                  <p class="form-group">
                    <label for="description">Description</label>
                    <textarea id="description" name="project[description]" class="form-control"></textarea>
                  </p>
                
                <p class="form-action " >
                  <%= f.submit  class:"btn btn-primary" %>
                </p>
          </div>
          <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/projects/show.html.erb
<% if user_signed_in? %>
        
      <div style=" background-color: rgba(0, 0, 255, 0.3); height:47px;">
        <br>
        <h2 style="text-align:center; ">
          Signed in as <%= current_user.first_name %>
        </h2><br>
      </div>
       
       <%# nav pannel %>
      <div style="display:flex; justify-content:center; background-color: rgba(0, 0, 255, 0.2); " >
        <p class="text-decoration-none m-4 btn btn-secondary ">
          <%= link_to "Welcome page", root_path, class: "text-decoration-none  text-white" %>
        </p>

        <%# <p class="text-decoration-none m-4 btn btn-secondary ">
          <%= link_to "project index", projects_path, class: "text-decoration-none  text-white"  %>
        <%# </p>  %>

        <p class="text-decoration-none m-4 btn btn-secondary ">
          <%= link_to "manage projects", index_path,class: "text-decoration-none  text-white" %>
        </p>

        <p class="text-decoration-none m-4 btn btn-secondary ">
          <%= link_to "edit project", edit_project_path(@project), class: "text-decoration-none  text-white"  %>
        </p>

        <%# affichage des projects %>     
          <%= form_tag project_path(@project), method: :delete do %>
            <p class="m-4">            
              <%= submit_tag "Delete this project", data: { confirm: "Êtes-vous sûr de vouloir supprimer ce projet ?" }, class: " btn btn-danger" %>
            </p>  
          <% end %>

        <p class="m-4">
          <%= link_to "Log out", logout_path, method: :delete, class: "text-decoration-none text-dark btn btn-danger text-white" %>
        </p>

      </div>

  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
      <br>

        <div> 
          <p class="text-center border-bottom text-muted border-primary">
              <span>
                <%=  @project.name %>
              </span>  <br> 
              <em style="opacity:0.7;">  
                <%= @project.description%>
              </em>
          </p>             
        </div>

      <!-- Affichage des utilisateurs affectés au projet -->
      <p >
        <h2>Users assigned to the project :</h2>
        <em >To add users to project, log in as admin<em>
      </p>

      <div style="display:flex;">  
        <ul>
          <% @project.users.each do |user| %>
            <p>
              <span>Name:    <%= user.first_name %></span><br>
              <em><%= user.email %></em>
            <p>
            <%# code de basculement %>
            <%= form_tag toggle_role_user_path(user), method: :put do %> 
              <% if user.role == 'user' %>
                  <%= submit_tag 'Pass as admin', class: 'btn btn-primary ' %><br>
              <% else %>
                  <%= submit_tag 'Pass as user', class: 'btn btn-secondary ' %>
              <% end %>
            <% end %>
          <% end %>
        </ul>

        <!-- Formulaire pour ajouter un utilisateur au projet -->
        <div style="margin-left:200px;">
            <% if current_user.role == 'admin' %>
              <%= form_with(url: project_add_user_path(@project), method: :post) do |f| %>
                <div class="form-group">
                  <%= f.label :email, "user mail" %>
                  <%= f.email_field :email, class: "form-control", required: true %>
                  <%= f.submit "add user", class:"btn btn-primary m-1" %>
                </div>
              <% end %>
            <% end %>
        </div>    
        </div>    
      </div>
    </div>
  </div>  


<% end %>